change in-game admin rank color to cyan
BalaM314/fish-commands pull request #37
Opened 2024-12-22 18:52 UTC by omnerom

2024-12-26 03:39 UTC, Brandons404 approved these changes
LGTM

2025-01-11 04:09 UTC, BalaM314 requested changes

2025-01-11 04:09 UTC, BalaM314 commented on src/ranks.ts
> +	static admin = new Rank("admin", 4, "Administrators with the power to ban players.", "[black]<[cyan]\uE82C[]>[]", "&lr[A]&fr", "[#C30202]");
You should also change the rank color (the last argument) to cyan. That will update the color in all the other commands.

2025-01-11 04:14 UTC, omnerom commented on src/ranks.ts
> +	static admin = new Rank("admin", 4, "Administrators with the power to ban players.", "[black]<[cyan]\uE82C[]>[]", "&lr[A]&fr", "[#C30202]");
Did that correctly I think.

2025-01-11 12:44 UTC, merged